server:
  port: 8081

spring:
  main:
    banner-mode: "off"
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
#    url: jdbc:h2:file:~/test
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org:
      springframework: ERROR